# Generated by Django 4.1.3 on 2022-11-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='languages',
            new_name='language',
        ),
    ]
